removing docker-credentials secret
IBM/the-mesh-for-data pull request #247
Opened 2021-01-03 10:38 UTC by shlomitk1

Signed-off-by: SHLOMITK@il.ibm.com

Fixes https://github.com/IBM/the-mesh-for-data/issues/210
- Removed the secret generation (docker-credentials)
- Removed attempts to login to the registry inside blueprint controller
- Removed references to docker variables inside motion webhooks

2021-01-03 19:18 UTC, roee88 approved these changes

2021-01-05 09:28 UTC, hunchback commented
@shlomitk1 - please revert the parts using the DOCKER_XXX in the controllers, this is not only useful for private registry but also for integration testing

2021-01-05 09:28 UTC, hunchback requested changes
reverts code in the controllers

2021-01-05 09:29 UTC, hunchback commented on manager/apis/motion/v1alpha1/batchtransfer_webhook.go
> -		} else {
revert

2021-01-05 09:29 UTC, hunchback commented on manager/apis/motion/v1alpha1/streamtransfer_webhook.go
> -		} else {
revert

2021-01-05 09:30 UTC, hunchback commented on manager/controllers/app/blueprint_controller.go
> -	hostname := os.Getenv("DOCKER_HOSTNAME")
revert

2021-01-05 10:12 UTC, shlomitk1 commented
> 
> 
> @shlomitk1 - please revert the parts using the DOCKER_XXX in the controllers, this is not only useful for private registry but also for integration testing

How is this useful for integration testing? hostname is only used for login to the registry. Since we don't login to private registry during integration tests, why would it matter?

2021-01-05 10:21 UTC, shlomitk1 commented on manager/controllers/app/blueprint_controller.go
> -	hostname := os.Getenv("DOCKER_HOSTNAME")
Why?

2021-01-06 09:03 UTC, hunchback commented
> > @shlomitk1 - please revert the parts using the DOCKER_XXX in the controllers, this is not only useful for private registry but also for integration testing
> 
> How is this useful for integration testing? hostname is only used for login to the registry. Since we don't login to private registry during integration tests, why would it matter?
> @hunchback Please provide comments inside #210 to continue discussion on what should be done.

As contra, consider the following, hostname is not just used for login:

```
                        hostname, b1 := os.LookupEnv("DOCKER_HOSTNAME")	
			namespace, b2 := os.LookupEnv("DOCKER_NAMESPACE")	
			tagname, b3 := os.LookupEnv("DOCKER_TAGNAME")	
			if b1 && b2 && b3 {	
				r.Spec.Image = hostname + "/" + namespace + "/mover:" + tagname	
			}
```

2021-01-06 09:16 UTC, hunchback commented on manager/controllers/app/blueprint_controller.go
> -	hostname := os.Getenv("DOCKER_HOSTNAME")
ok, fine, this can be removed

2021-01-06 10:18 UTC, shlomitk1 commented
> 
> 
> > > @shlomitk1 - please revert the parts using the DOCKER_XXX in the controllers, this is not only useful for private registry but also for integration testing
> > 
> > 
> > How is this useful for integration testing? hostname is only used for login to the registry. Since we don't login to private registry during integration tests, why would it matter?
> > @hunchback Please provide comments inside #210 to continue discussion on what should be done.
> 
> As contra, consider the following, hostname is not just used for login:
> 
> ```
>                         hostname, b1 := os.LookupEnv("DOCKER_HOSTNAME")	
> 			namespace, b2 := os.LookupEnv("DOCKER_NAMESPACE")	
> 			tagname, b3 := os.LookupEnv("DOCKER_TAGNAME")	
> 			if b1 && b2 && b3 {	
> 				r.Spec.Image = hostname + "/" + namespace + "/mover:" + tagname	
> 			}
> ```

Unnecessary. Mover image can be constructed using MOVER_IMAGE env var, and according to @froesef we don't need yet another way.

2021-01-06 10:53 UTC, hunchback approved these changes

2021-01-06 13:29 UTC, froesef commented
> > > > @shlomitk1 - please revert the parts using the DOCKER_XXX in the controllers, this is not only useful for private registry but also for integration testing
> > > 
> > > 
> > > How is this useful for integration testing? hostname is only used for login to the registry. Since we don't login to private registry during integration tests, why would it matter?
> > > @hunchback Please provide comments inside #210 to continue discussion on what should be done.
> > 
> > 
> > As contra, consider the following, hostname is not just used for login:
> > ```
> >                         hostname, b1 := os.LookupEnv("DOCKER_HOSTNAME")	
> > 			namespace, b2 := os.LookupEnv("DOCKER_NAMESPACE")	
> > 			tagname, b3 := os.LookupEnv("DOCKER_TAGNAME")	
> > 			if b1 && b2 && b3 {	
> > 				r.Spec.Image = hostname + "/" + namespace + "/mover:" + tagname	
> > 			}
> > ```
> 
> Unnecessary. Mover image can be constructed using MOVER_IMAGE env var, and according to @froesef we don't need yet another way.

I think the way to go here for customization is what @hunchback started at some point. To make it possible to define this in the module definition. (thus to customize the deployed helm charts in the module definition) (just fyi. This is independent of this issue)

2021-01-06 13:29 UTC, froesef approved these changes

2021-01-06 13:51 UTC, merged