Egeria Documentation changes
IBM/the-mesh-for-data pull request #462
Opened 2021-03-24 07:16 UTC by rohithdv

This PR changes the default egeria meta data server to "mds1" in the documentation as per new changes done is #394. 
Signed-off-by: rohithdv <rovallam@in.ibm.com>

2021-03-24 12:41 UTC, shlomitk1 approved these changes

2021-04-01 13:23 UTC, ronenkat approved these changes

2021-04-02 12:41 UTC, roee88 requested changes
Please make the change in site/ dir too. The website dir will soon be removed.

2021-04-02 18:03 UTC, rohithdv commented
> Please make the change in site/ dir too. The website dir will soon be removed.

Fixed. Please check. Thanks.

2021-04-03 17:22 UTC, roee88 approved these changes

2021-04-03 17:23 UTC, merged